### ISSUE TITLE
Mobile app using API REST

### ISSUE THREAD

**Issue by stefancvetkovic** [pixelit-project/PixelIt#133]
I was thinking to create a mobile app that will hit API REST methods and to present text entrance, emoji picking and color wheel something like that. 
Is it a doable with REST API? Thanks

**Comment by stefancvetkovic** [comment]
Thanks, but I didnt find any kind of authentication for this REST API? I mean anybody with postman, and ip address of the device can access it's controls?

**Comment by o0shojo0o** [comment]
Yes the Pixelit is designed for local use.

**Comment by stefancvetkovic** [comment]
Yes, I know. But that's not quite secure. Those api REST should contains only username/pass at least in its header for each request..

**Comment by o0shojo0o** [comment]
Yes, this could be extended optionally, but I have hardly any resources left for this project at the moment, so I can't implement it at the moment :(
