### ISSUE TITLE
Feature request: allow to remove the small bars below the clock

### ISSUE THREAD

**Issue by jghaanstra** [pixelit-project/PixelIt#181]
Great project, just sponsored it a little.

What is the purpose of the small bars below the clock ? I would like to see a feature to remove them in both the settings and through the API.

**Comment by o0shojo0o** [comment]
Hi, 
the bars are the days of the week. 
And if you use the "Big clock font" no weekdays should be displayed anymore.

![image](https://user-images.githubusercontent.com/19333515/183513456-67f41392-a625-4e57-9b34-fc6fc340afee.png)

**Comment by jghaanstra** [comment]
> the bars are the days of the week.

Ah right, makes sense now. I'm aware using the big clock wil remove the bars but I'd still like to see an option to use the small clock without the bars though if it's not too complicated to add.

**Comment by o0shojo0o** [comment]
I will have a look at it the days, I think that it does not need so much effort.

**Comment by o0shojo0o** [comment]
available in version 1.1.0
