### ISSUE TITLE
Feature request: more switch animations like slide

### ISSUE THREAD

**Issue by jghaanstra** [pixelit-project/PixelIt#182]
I'd like to see more switch animations like slide down (this already works for the clock / date transition), slide left, slide right, slide up and pixelate.

**Comment by o0shojo0o** [comment]
Hi, 
the bars are the days of the week. 
And if you use the "Big clock font" no weekdays should be displayed anymore.

![image](https://user-images.githubusercontent.com/19333515/183513456-67f41392-a625-4e57-9b34-fc6fc340afee.png)
