### ISSUE TITLE
Led matrix 8x32 does not produce anything

### ISSUE THREAD

**Issue by stefancvetkovic** [pixelit-project/PixelIt#183]
This is my wiring following basic wiring diagram from here 
![image](https://user-images.githubusercontent.com/13699747/158705041-b4c243e7-f641-408c-b2f6-e0962f303123.png)

https://drive.google.com/file/d/1PaB70lPk9wc0sXvMmthXiuZWd9fsIkHr/view?usp=sharing

I have 5v on my esp8266 and on my entering point on my LED strip, I can access to Pixelit Control dashboard, but when I try to send in TestArea some t4ext or anything. My ledstrip is off whole the time? thanks

**Comment by o0shojo0o** [comment]
Are there still problems here?
