### ISSUE TITLE
No output on firmware 1.1.0

### ISSUE THREAD

**Issue by jghaanstra** [pixelit-project/PixelIt#186]
I just updated to firmware 1.1.0 through the Web UI but it's not working as expected. There is no output shown on the LED matrix anymore other than a couple of dots which are visible upon reboot. WebUI is working fine, REST API is working fine, MQTT is working fine but nothing is shown.

I tried a factory reset to no avail. Even tried reverting the firmware to 1.0.0 and tried a clean flash of the Wemos D1 Mini but that hasnt worked either.

Did the update break my matrix (which I think is strange as it does show the initial loading dots)?

**Comment by o0shojo0o** [comment]
My two PixelIt show no errors, you could try the [CleanFlash.bin](https://pixelit-project.github.io/firmware.html#flashing).

**Comment by jghaanstra** [comment]
Found the issue, my Wemos D1 Mini is having identity issues. When I first connected the matrix I had to connect it to pin D5 (which was different to the documentation). With the update I had to revert back to pin D2 to make the LED matrix work. Strange.

**Comment by o0shojo0o** [comment]
This is really strange, but no matter main thing :)
