### ISSUE TITLE
sleepMode command stopped working

### ISSUE THREAD

**Issue by Rushmed** [pixelit-project/PixelIt#187]
Hi,

did not know exactly when since when but MQTT sleepMode command does not work anymore for me.
`{
    "sleepMode": true
}
` 
I am on V1.1.

Went back to V1.0 and 0.4 without success.

What can I do?

**Comment by o0shojo0o** [comment]
Hi, 
I don't have MQTT in use, but tried it via the API.
There it works!

to which MQTT Topic do you send it?

**Comment by Rushmed** [comment]
PixelIt1/setScreen

**Comment by Rushmed** [comment]
Found the problem.
Sorry mister!
Had an issue with my ioBroker mqtt instance.
Deleting and new creating fixed it.
