### ISSUE TITLE
ESP32 Fixes

### ISSUE THREAD

**Issue by TravisRoy** [pixelit-project/PixelIt#226]
Unable to save config fix:

```
    // Mounting FileSystem
    Serial.println(F("Mounting file system..."));
#if defined(ESP8266)
    if (LittleFS.begin())
#elif defined(ESP32)
    #define FORMAT_SPIFFS_IF_FAILED true
    if (SPIFFS.begin(FORMAT_SPIFFS_IF_FAILED))
    
#endif
```

Wifi AP fix:

```
  // Hostname
    if (hostname.isEmpty())
    {
        hostname = "PixelIt";
        
    }
    WiFi.hostname(hostname);

    WiFi.mode(WIFI_AP);

    wifiManager.setAPCallback(EnteredHotspotCallback);
    wifiManager.setMinimumSignalQuality();
    // Timout for the wifi connection until the hotspot is set up
```

**Comment by Bettman66** [comment]
Thank you, it works.

**Comment by o0shojo0o** [comment]
@rliegmann can you evaluate if this fix is still necessary?

**Comment by rliegmann** [comment]
@TravisRoy FORMAT_SPIFFS_IF_FAILED is useful. It can happen that the memory is not initialized. I'd say we'll take over.

Why do you think we need WiFi.mode(WIFI_AP)? I just tried it with a new ESP32 and it builds the AP cleanly. What problems did you have?

**Comment by DSRocker** [comment]
I tried the new release (firmware_v2.2-beta-ONEWIRE_wemos_d1_mini32.bin) with a new ESP32 Dev Kit C V4. 
No AP

**Comment by DSRocker** [comment]
I get everytime this error in serial monitor: (no AP)
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371
ets Jun  8 2016 00:22:57

**Comment by rliegmann** [comment]
Have you tried completely clearing the memory of the ESP?
Then flashed again?

**Comment by DSRocker** [comment]
Yes, I did! And I tried another esp32.. the same errors

**Comment by commputethis** [comment]
I get the same thing.  I have tried on 3 different ESP32 device models (multiple boards of each model) and get the same error @DSRocker was getting.

**Comment by foorschtbar** [comment]
> I get the same thing.  I have tried on 3 different ESP32 device models (multiple boards of each model) and get the same error @DSRocker was getting.

Please try the a full upgrade from the webflasher (se documentation) and select the erase option. We have many working esp32, that must be a filesystem error related to missing/wrong formatting

**Comment by commputethis** [comment]
I've done that and no change. I've tried from an Ubuntu machine and a Windows machine. I've tried from two different networks too (two different Internet providers also). One of the networks had no filtering to make sure something wasn't getting blocked.

I've also tried downloading and flashing. Esp8266 devices work without issue. It's only esp32 that I can't get to work.

**Comment by foorschtbar** [comment]
Could you post the serial log after flashing with webflasher?

**Comment by commputethis** [comment]
Well, I had found something online about SPIFFS and found for many that flashing it with the SPIFFS_Test.ino and then flashing with the actual config wanted fixes it.  Now, I am not getting that error, but one about unknown pins for D3 and D1.  I have attached the logs from a generic esp32 board and a wemo d1 mini esp32 board.  Both have the same errors.  Probably need to do a new problem since it is now a different error.
[esp-web-tools-logs-wemos-d1-mini-esp32.txt](https://github.com/pixelit-project/PixelIt/files/13629247/esp-web-tools-logs-wemos-d1-mini-esp32.txt)
[esp-web-tools-logs-generic-esp32.txt](https://github.com/pixelit-project/PixelIt/files/13629248/esp-web-tools-logs-generic-esp32.txt)

**Comment by commputethis** [comment]
Looking at the boards, neither one has a D1 or D3 pin.
![20231210_162345](https://github.com/pixelit-project/PixelIt/assets/17625274/12c24122-68d3-4c9b-9396-057d6f40cdc8)
![20231210_162336](https://github.com/pixelit-project/PixelIt/assets/17625274/036782f8-7405-41d8-b1b9-b78ae1481fe7)

**Comment by commputethis** [comment]
I guess it could be the ```[BH1750] ERROR: other error``` that is causing the issue.
