### ISSUE TITLE
The matrix keeps dark 

### ISSUE THREAD

**Issue by davidlamd89** [pixelit-project/PixelIt#229]
I'm trying to get this to work, I've followed the instructions, but the 8x32 matrix keeps dark, I tried with different boards (Wemos D1 mini clones), I also tried to feed the Matrix only with USB or with an external power source, but I still can't get it to work.
The matrix lights up when using WLED, so i believe it's a configuration problem.

Can someone help me? 

Thanks in advance

**Comment by o0shojo0o** [comment]
Did you use the [firmware_v2.1.2_d1_mini.bin](https://github.com/pixelit-project/PixelIt/releases/download/2.1.2/firmware_v2.1.2_d1_mini.bin)?

**Comment by davidlamd89** [comment]
> Did you use the [firmware_v2.1.2_d1_mini.bin](https://github.com/pixelit-project/PixelIt/releases/download/2.1.2/firmware_v2.1.2_d1_mini.bin)?

Yes I did.
 I've solved the problem, I had to use pin D4 instead of D2 as described in Wiki. 

Thank you for taking the time on trying to help.
