### ISSUE TITLE
OneWire breaks I2C

### ISSUE THREAD

**Issue by miccgn** [pixelit-project/PixelIt#241]
Hi,

in the default settings, the onewire pins is one of the i2c pins. That's fine if you use no I2C sensors, or both I2C light sensors and I2C temperature sensors.

However, once you use only an I2C light sensor and no I2C temperature sensor, PixelIt next probes for an DHT sensor per OneWire. The communcation on I2C already had been established, but as Onewire uses the same pin, will be broken now, no matter whether there's an DHT or not.

Fix has been provided in PR https://github.com/pixelit-project/PixelIt/pull/240/commits/8205dc9807bbe50ac77477364acf33d5b57c963e. However, I killed my fork, which also removed the PR. @o0shojo0o: can you simply include the fix (which still can be read in the PR) with one of your next PRs?

**Comment by o0shojo0o** [comment]
Thanks for that, I've put it in.
