### ISSUE TITLE
mDNS Support?

### ISSUE THREAD

**Issue by darrenparkinson** [pixelit-project/PixelIt#256]
Just wondering if it's possible to add, if not already there, mDNS / Bonjour support for discovery by name?

I tried running `dns-sd -B _services._dns-sd._udp` and the device doesn't seem to show up. 

Is it possible it's already there, I'm just doing it wrong?

Many thanks.

**Comment by aptonline** [comment]
Doesn't mDNS/Bonjour use port 5353? Erin my port scan it doesn't seem to be exposed currently.  Would be a  useful addition :)
