### ISSUE TITLE
How long are messages shown for?

### ISSUE THREAD

**Issue by rozza-m** [pixelit-project/PixelIt#257]
Hi, I'm back :)

I can't work out from the code what controls how long a text string sent via the API is shown for. Is there any control over it? There's a Forcedduration variable but it seems permanently set to zero.

**Comment by o0shojo0o** [comment]
The text will be displayed until something new comes, or you have activated the 'Clock auto fallback'.

![image](https://user-images.githubusercontent.com/19333515/217037190-aa6ced90-3527-4950-927b-5b96583450c4.png)

**Comment by rozza-m** [comment]
Of course. Thanks!
