### ISSUE TITLE
Feature Request: Update notifications on HomeAssistant

### ISSUE THREAD

**Issue by fmunozs** [pixelit-project/PixelIt#262]
hello

I got my pixie hooked on mqttd with my homeassistant. I thing a good feature is to get the notification about  new firmware into my homeassistant app.

It currently supports it with other kind of devices, 

![image](https://user-images.githubusercontent.com/1041604/218326002-471bc0f5-2be6-469d-9a27-b65e4dbf5d6e.png)

Regards

**Comment by aptonline** [comment]
Should be straight forward to implement as PixelIt integrates into HA using MQTT discovery. This exposes a number of sensors including the current version of firmware which you should be able to watch via an automation.

![0B6D11A8-521C-4ACC-AF1B-ED1CEB0BDF1C](https://user-images.githubusercontent.com/190136/219127318-d898e9e5-1a84-467d-b532-bd75b721f9f6.jpeg)
