### ISSUE TITLE
Scrolling Text Speed

### ISSUE THREAD

**Issue by ThomasTom86** [pixelit-project/PixelIt#270]
First of all, thanks for the great project.  I use pixelit in connection with the iobroker.  For simple messages, I use the DP "Message" in Iobroker.  Is it possible to adjust the speed via this DP?  The speed is too fast for my text, it is difficult to read.  Thx

**Comment by rliegmann** [comment]
Hi, I think this has nothing to do with the PixelIT firmware. Since I don't use ioBroker I can't say how it communicates. But I think they also work with the REST API. I think you can specify the speed in this. Maybe ioBroker has to adjust something.

**Comment by Rushmed** [comment]
@ThomasTom86 You have to use ext_message DP, for example:

`{   "text": {     "textString": "Krach im Kinderzimmer!",     "bigFont": true,     "scrollText": "auto",     "scrollTextDelay": 60,     "hexColor": "#FF0000"   } }`
