### ISSUE TITLE
bme680 Reading Backwards?

### ISSUE THREAD

**Issue by Keshin1988** [pixelit-project/PixelIt#285]
hey all im unsure if this is my scenario but i feel like the voc reading on my bme680 is reading in reverse?
according to the index  sheet it shows
![BME680 IAQ classification and color-coding](https://github.com/pixelit-project/PixelIt/assets/114125729/19fc884c-f668-43c4-baac-d8ac8c42153b)

my findings are outside in fresh clean air im getting approx 200-210kohm if i directly breath onto it, trying to exhale (increase CO2) the level drops considerably to 100kohms 

according to the index above shouldn't my value be increasing rather than decreasing when i breath on it

**Comment by Keshin1988** [comment]
It's 6am in the morning and it's been left outside in the clean air all night and this is the results I am getting now. 
![Screenshot_20230523_060056_Home Assistant](https://github.com/pixelit-project/PixelIt/assets/114125729/a33e713a-728d-4379-af04-1e0886472809)

**Comment by foorschtbar** [comment]
I have no BME680 try test it, but you can upload a clean example sketch and test only the BME680.
