### ISSUE TITLE
MQTT setScreen only works if the master topic ends with "/"

### ISSUE THREAD

**Issue by oxivanisher** [pixelit-project/PixelIt#301]
I just realized, that (at least the `setScreen`) command only works if the configured Master topic in the config ends with a "/". I realized this because I took a look at the [code](https://github.com/pixelit-project/PixelIt/blob/3b7f2d9076d35d691d2dd022745b37986136b7a3/src/PixelIt.ino#L1006). I don't know if it would be better to modify the mentioned source or to ensure the config ends with a "/" on settings change.

**Comment by foorschtbar** [comment]
Thank u. Is now fixed in master branch and will be available with the next release.
