### ISSUE TITLE
Feature request:  config backup/restore

### ISSUE THREAD

**Issue by jekader** [pixelit-project/PixelIt#319]
Would be nice to have a feature to dump/restore the config - this makes upgrades safer and also allows to clone settings across different devices.  It can be done in the web UI directly to also lint the config before applying to avoid bricking the device.

**Comment by foorschtbar** [comment]
Good idea. API for this should already be there, would just be some work in the WebUI. Maybe @o0shojo0o want to have a look at it?

**Comment by o0shojo0o** [comment]
is available in the current beta https://github.com/pixelit-project/PixelIt/releases/tag/2.4.5-beta

**Comment by jekader** [comment]
Thank you, updated to 2.4.5 and I can confirm that the backup/restore option is now available in the WebUI and working!
