### ISSUE TITLE
Unable to turn off LEDs

### ISSUE THREAD

**Issue by jimmyeao** [pixelit-project/PixelIt#323]
After the latest update, my Homeassistant service to turn off the display no longer works? (Integrated via MQTT)

**Comment by jimmyeao** [comment]
to add, using HA to manually set the state, I can turn it off:
![image](https://github.com/pixelit-project/PixelIt/assets/5197831/ce7ce86e-2345-4986-a940-ab1c00551bf9)

I dont have this issue with any other MQTT devices, they turn on and off as expected

**Comment by jimmyeao** [comment]
rolled back to 2.3.2, fixes it for now

**Comment by gaetanars** [comment]
Same issue here on D1 Mini

**Comment by foorschtbar** [comment]
I dont use HA. Are you firm with mqtt? I need the mqtt payload you send to turn on/off the leds. With node red the sleep mode works without problems..

**Comment by gaetanars** [comment]
The MQTT Payload is available throught homeassistant discovery that is define here : https://github.com/pixelit-project/PixelIt/blob/e6865d9c2310d2aac153e26a082d9608bc8b9071/src/PixelIt.ino#L2943-L2984

**Comment by foorschtbar** [comment]
Hey guys, you all have Hassio running?

**Comment by jimmyeao** [comment]
I do...

> Hey guys, you all have Hassio running?

**Comment by jimmyeao** [comment]
When i try and turn off from Hassio, it sends 
setScreen = {'sleepMode': true}
![image](https://github.com/pixelit-project/PixelIt/assets/5197831/84356cb3-4ee6-4284-82b3-33eccc2ef712)

But doesnt turn off the screen

**Comment by gaetanars** [comment]
The error in the pixels is : 
```
[2023-11-05T18:52:32] MQTT_callback: JSON length mismatch! JSON Message to long :(
[2023-11-05T18:52:32] MQTT_callback: Incoming JSON (Topic: Haus/PixelIt/setScreen, Length: 19/18) 
```

**Comment by foorschtbar** [comment]
Please test the [2.4.6-beta](https://github.com/pixelit-project/PixelIt/releases/tag/2.4.6-beta) release and give us feedback

**Comment by jimmyeao** [comment]
The Beta fixes it for me :)

> Please test the [2.4.6-beta](https://github.com/pixelit-project/PixelIt/releases/tag/2.4.6-beta) release and give us feedback

**Comment by jimmyeao** [comment]
Will there be a further fix for brightness?

**Comment by foorschtbar** [comment]
Ups, i closed the wrong issue. I will check the brightness issue soon.

**Comment by foorschtbar** [comment]
i see the problem. i optimized the code and sleep mode on/off cant combined with other options now. The brightness will be restored when sleep mode ended. To set a new brightness, you could send them alone. Do you need the option to send end sleepmode and set a new brightness?

**Comment by jimmyeao** [comment]
> i see the problem. i optimized the code and sleep mode on/off cant combined with other options now. The brightness will be restored when sleep mode ended. To set a new brightness, you could send them alone. Do you need the option to send end sleepmode and set a new brightness?

Yes, the way Hassio send the command (for some reason) is
`setScreen = {'sleepMode': false, 'brightness': 201} `regardless of the sleepmode, its sending them together

**Comment by foorschtbar** [comment]
Please test the [2.4.8-beta](https://github.com/pixelit-project/PixelIt/releases/tag/2.4.8-beta) release and give us feedback.

**Comment by jimmyeao** [comment]
> Please test the [2.4.8-beta](https://github.com/pixelit-project/PixelIt/releases/tag/2.4.8-beta) release and give us feedback.

Will test this afternoon, thank you :)

**Comment by foorschtbar** [comment]
I close this topic now. Feel free to reopen if the problem with the latest 2.5.0 release still appears.
