### ISSUE TITLE
Color always black

### ISSUE THREAD

**Issue by Pissbirne** [pixelit-project/PixelIt#373]
After update to firmware_v2.5.2_ESP8266_generic.bin the display only shows the boot screen.
The reason is that the color is black (#000000). its not posible to change. after change , save config and the reboot its black again.

**Comment by foorschtbar** [comment]
which hash (md%) had you firmware_v2.5.2_ESP8266_generic.bin?

**Comment by Pissbirne** [comment]
1793EDABEF2230A46EE30338DC94110F

**Comment by foorschtbar** [comment]
we check. its a bug in the UI. the changed color is not send to the device

**Comment by Pissbirne** [comment]
OK thank you.

**Comment by o0shojo0o** [comment]
With 2.5.3 the problem is fixed, can you please test it?

**Comment by Pissbirne** [comment]
yes works fine.
