### ISSUE TITLE
PixelIt 2.5.3 with Ulanzi

### ISSUE THREAD

**Issue by JediMax27** [pixelit-project/PixelIt#376]
Today I install PixelIt 2.5.3 on Ulanzi clock. I have 2 problem with it
1. I try to upgrade firmware from 2.5.1 (use https://pixelit-project.github.io/firmware.html) with no success. It working only when I flash it with "first install" option.
2. when Ulanzi connect to power from usb, on web interface I see too big Luminance (like 623586 lux.) But if I deconnect Usb, luminance is somthing like 1114 lux

**Comment by foorschtbar** [comment]
1. The web updater is only for "fresh" installations. Normal updates could done on the WebUI of the PixelIT under `Update & Backup` on the left side.
2. Do you had the same behavior with 2.5.1?

**Comment by JediMax27** [comment]
1. Ok, thank you
2. As I remember, no

**Comment by foorschtbar** [comment]
Please downgrade to 2.5.1 check this for us :)

**Comment by Jurich2004** [comment]
I have PixelIT 2.5.1 on ESP8266_d1_mini and I try to update via WebUI of the PixelIT under Update & Backup to version 2.5.3. After pressing the update button the firmware device freezes and reboot helps. Update does not happen, still version 2.5.1.
Similarly, I updated PixelIT 2.5.1 on ESP32_d1_mini32 and everything was fine there. The update happened.

**Comment by foorschtbar** [comment]
We had over 250 updates without issues, please try it via cable (web flasher). it might be a problem with your device or a corrupt file.
