### ISSUE TITLE
Combine centerText with scrollText=auto

### ISSUE THREAD

**Issue by miccgn** [pixelit-project/PixelIt#96]
It would be a nice enhancement if I could specify both "centerText=true" and "scrollText=auto".

Expected behaviour:
- if text fits into display: center it, no scrolling
- if text does not fit into display: ignore centering, start scrolling

Difference to now is that text that fits will be centered, not adjusted left.

I have some ideas how to do this, but this requires redesign of all the DrawText... functions.

**Comment by o0shojo0o** [comment]
Yes, it would have to completely rebuild DrawText.
But I couldn't motivate myself to do it yet. 
I had started it once before, but discarded it due to lack of time.

**Comment by miccgn** [comment]
Still would be an useful extension

**Comment by foorschtbar** [comment]
@miccgn please test the latest beta: https://github.com/pixelit-project/PixelIt/releases/tag/2.3.2-beta

**Comment by foorschtbar** [comment]
Fixed with latest (2.3.2) release

**Comment by miccgn** [comment]
Thanks!
Sorry, didn't find time to test it yet 😕😕
